import json

nb = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "beam-title",
   "metadata": {},
   "source": [
    "# Simply Supported Beam Analysis (Concentrated Loading)\n",
    "This tool calculates and plots the Loading, Shear, Moment, Slope, and Deflection for a simply supported beam with a single concentrated load.\n",
    "\n",
    "### Formulas derived from Norton Machine Design 6e, Case (a):"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "beam-code",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ==========================================\n",
    "# 1. INPUT VALUES\n",
    "# ==========================================\n",
    "F = 1000      # Force (N)\n",
    "l = 1.0       # Total length of beam (m)\n",
    "a = 0.4       # Distance from left support to load (m)\n",
    "E = 200e9     # Modulus of Elasticity (Pa) - e.g., Steel\n",
    "I = 1e-6      # Moment of Inertia (m^4)\n",
    "\n",
    "# ==========================================\n",
    "# 2. CALCULATIONS\n",
    "# ==========================================\n",
    "\n",
    "# Singularity function helper: <x - a>^n\n",
    "def macaulay(x, a, n):\n",
    "    return np.where(x > a, (x - a)**n, 0.0)\n",
    "\n",
    "# Reactions\n",
    "R1 = F * (1 - a/l)\n",
    "R2 = F * (a/l)\n",
    "\n",
    "# x-coordinates\n",
    "x = np.linspace(0, l, 1000)\n",
    "\n",
    "# Shear Force V(x)\n",
    "V = R1 - F * macaulay(x, a, 0)\n",
    "\n",
    "# Bending Moment M(x)\n",
    "M = R1 * x - F * macaulay(x, a, 1)\n",
    "\n",
    "# Slope theta(x)\n",
    "const_theta = (a / (3 * l)) * (-a**2 + 3 * a * l - 2 * l**2)\n",
    "theta = (F / (2 * E * I)) * ((1 - a/l) * x**2 - macaulay(x, a, 2) + const_theta)\n",
    "\n",
    "# Deflection y(x)\n",
    "# Integration of theta(x) where y(0) = 0\n",
    "y = (F / (6 * E * I)) * ((1 - a/l) * x**3 - macaulay(x, a, 3) + 3 * const_theta * x)\n",
    "\n",
    "# Key values\n",
    "V_max = max(abs(R1), abs(R2))\n",
    "M_max = F * a * (1 - a/l)\n",
    "y_at_a = (F / (3 * E * I)) * (2 * a**3 - (a**4 / l) - l * a**2) # Deflection at load point\n",
    "\n",
    "print(f\"Reactions: R1 = {R1:.2f} N, R2 = {R2:.2f} N\")\n",
    "print(f\"Max Moment: {M_max:.2f} Nm\")\n",
    "print(f\"Deflection at load point (y_max): {y_at_a*1000:.4f} mm\")\n",
    "\n",
    "# ==========================================\n",
    "# 3. PLOTTING\n",
    "# ==========================================\n",
    "fig, axs = plt.subplots(4, 1, figsize=(10, 12), sharex=True)\n",
    "plt.subplots_adjust(hspace=0.4)\n",
    "\n",
    "# Shear Diagram\n",
    "axs[0].plot(x, V, color='red', linewidth=2)\n",
    "axs[0].fill_between(x, V, color='red', alpha=0.1)\n",
    "axs[0].axhline(0, color='black', linewidth=1)\n",
    "axs[0].set_ylabel('Shear Force V (N)')\n",
    "axs[0].set_title('Shear Diagram')\n",
    "axs[0].grid(True, linestyle='--', alpha=0.6)\n",
    "\n",
    "# Moment Diagram\n",
    "axs[1].plot(x, M, color='blue', linewidth=2)\n",
    "axs[1].fill_between(x, M, color='blue', alpha=0.1)\n",
    "axs[1].axhline(0, color='black', linewidth=1)\n",
    "axs[1].set_ylabel('Moment M (Nm)')\n",
    "axs[1].set_title('Moment Diagram')\n",
    "axs[1].grid(True, linestyle='--', alpha=0.6)\n",
    "\n",
    "# Slope Diagram\n",
    "axs[2].plot(x, theta, color='green', linewidth=2)\n",
    "axs[2].fill_between(x, theta, color='green', alpha=0.1)\n",
    "axs[2].axhline(0, color='black', linewidth=1)\n",
    "axs[2].set_ylabel('Slope theta (rad)')\n",
    "axs[2].set_title('Slope Diagram')\n",
    "axs[2].grid(True, linestyle='--', alpha=0.6)\n",
    "\n",
    "# Deflection Diagram\n",
    "axs[3].plot(x, y * 1000, color='purple', linewidth=2) # plot in mm\n",
    "axs[3].fill_between(x, y * 1000, color='purple', alpha=0.1)\n",
    "axs[3].axhline(0, color='black', linewidth=1)\n",
    "axs[3].set_ylabel('Deflection y (mm)')\n",
    "axs[3].set_xlabel('Beam Position x (m)')\n",
    "axs[3].set_title('Deflection Diagram')\n",
    "axs[3].grid(True, linestyle='--', alpha=0.6)\n",
    "\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('BeamAnalysisTool.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)
