import json

nb = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Beam Analyzer\n",
    "This tool analyzes simply supported beams under different loading conditions using Norton Machine Design 6e formulas."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Case (a): Concentrated Loading\n",
    "A single force $F$ applied at distance $a$ from the left support."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ==========================================\n",
    "# 1. INPUT VALUES - Case (a)\n",
    "# ==========================================\n",
    "F = 1000      # Force (N)\n",
    "l = 1.0       # Total length of beam (m)\n",
    "a = 0.4       # Distance from left support to load (m)\n",
    "E = 200e9     # Modulus of Elasticity (Pa)\n",
    "I = 1e-6      # Moment of Inertia (m^4)\n",
    "\n",
    "def macaulay(x, a, n):\n",
    "    return np.where(x > a, (x - a)**n, 0.0)\n",
    "\n",
    "x = np.linspace(0, l, 1000)\n",
    "R1 = F * (1 - a/l)\n",
    "R2 = F * (a/l)\n",
    "V = R1 - F * macaulay(x, a, 0)\n",
    "M = R1 * x - F * macaulay(x, a, 1)\n",
    "const_theta = (a / (3 * l)) * (-a**2 + 3 * a * l - 2 * l**2)\n",
    "theta = (F / (2 * E * I)) * ((1 - a/l) * x**2 - macaulay(x, a, 2) + const_theta)\n",
    "y = (F / (6 * E * I)) * ((1 - a/l) * x**3 - macaulay(x, a, 3) + 3 * const_theta * x)\n",
    "\n",
    "# ==========================================\n",
    "# 3. PLOTTING\n",
    "# ==========================================\n",
    "fig, axs = plt.subplots(5, 1, figsize=(10, 15), sharex=True)\n",
    "plt.subplots_adjust(hspace=0.6)\n",
    "\n",
    "# 0. Free Body Diagram (FBD)\n",
    "ax = axs[0]\n",
    "ax.plot([0, l], [0, 0], 'black', lw=4) # Beam\n",
    "# Reactions R1 and R2\n",
    "ax.annotate(f'R1={R1:.0f}N', xy=(0, 0), xytext=(0, 0.5), arrowprops=dict(arrowstyle='->', lw=2, color='green'), ha='center')\n",
    "ax.annotate(f'R2={R2:.0f}N', xy=(l, 0), xytext=(l, 0.5), arrowprops=dict(arrowstyle='->', lw=2, color='green'), ha='center')\n",
    "# Applied Force F\n",
    "ax.annotate(f'F={F:.0f}N', xy=(a, 0), xytext=(a, -0.5), arrowprops=dict(arrowstyle='->', lw=2, color='red'), ha='center')\n",
    "ax.axvline(a, color='red', linestyle=':', alpha=0.5) # Location dash\n",
    "ax.set_xticks([0, a, l])\n",
    "ax.xaxis.tick_top()\n",
    "ax.xaxis.set_label_position('top')\n",
    "ax.set_xlabel('Position x (m)')\n",
    "ax.set_ylim(-1, 1)\n",
    "ax.set_title('Free Body Diagram & Loading', pad=40)\n",
    "ax.spines['left'].set_visible(False)\n",
    "ax.spines['right'].set_visible(False)\n",
    "ax.spines['bottom'].set_visible(False)\n",
    "ax.get_yaxis().set_visible(False)\n",
    "\n",
    "# 1. Shear\n",
    "axs[1].plot(x, V, 'r'); axs[1].fill_between(x, V, color='r', alpha=0.1); axs[1].set_ylabel('Shear (N)')\n",
    "axs[1].grid(True, alpha=0.3); axs[1].axhline(0, color='k', lw=1)\n",
    "\n",
    "# 2. Moment\n",
    "axs[2].plot(x, M, 'b'); axs[2].fill_between(x, M, color='b', alpha=0.1); axs[2].set_ylabel('Moment (Nm)')\n",
    "axs[2].grid(True, alpha=0.3); axs[2].axhline(0, color='k', lw=1)\n",
    "\n",
    "# 3. Slope\n",
    "axs[3].plot(x, theta, 'g'); axs[3].fill_between(x, theta, color='g', alpha=0.1); axs[3].set_ylabel('Slope (rad)')\n",
    "axs[3].grid(True, alpha=0.3); axs[3].axhline(0, color='k', lw=1)\n",
    "\n",
    "# 4. Deflection\n",
    "axs[4].plot(x, y*1000, 'purple'); axs[4].fill_between(x, y*1000, color='purple', alpha=0.1); axs[4].set_ylabel('Deflection (mm)')\n",
    "axs[4].grid(True, alpha=0.3); axs[4].axhline(0, color='k', lw=1); axs[4].set_xlabel('Position x (m)')\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Case (b): Uniformly Distributed Loading\n",
    "A distributed load $w$ starting at distance $a$ and continuing to the end of the beam."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ==========================================\n",
    "# 1. INPUT VALUES - Case (b)\n",
    "# ==========================================\n",
    "w_load = 5000  # Load intensity (N/m)\n",
    "l = 1.0        # Total length of beam (m)\n",
    "a = 0.3        # Start of distributed load (m)\n",
    "E = 200e9      # Modulus of Elasticity (Pa)\n",
    "I = 1e-6       # Moment of Inertia (m^4)\n",
    "\n",
    "def macaulay(x, a, n):\n",
    "    return np.where(x > a, (x - a)**n, 0.0)\n",
    "\n",
    "x = np.linspace(0, l, 1000)\n",
    "R1 = (w_load / (2 * l)) * (l - a)**2\n",
    "R2 = (w_load / (2 * l)) * (l**2 - a**2)\n",
    "V = w_load * ( (1/(2*l))*(l-a)**2 - macaulay(x, a, 1) )\n",
    "M = (w_load / 2) * ( (x/l)*(l-a)**2 - macaulay(x, a, 2) )\n",
    "term_const = (1/l) * ( (l-a)**4 - 2*(l**2)*((l-a)**2) )\n",
    "theta = (w_load / (24 * E * I)) * ( (6*(x**2)/l)*(l-a)**2 - 4*macaulay(x, a, 3) + term_const )\n",
    "y = (w_load / (24 * E * I)) * ( (2*(x**3)/l)*(l-a)**2 - macaulay(x, a, 4) + (x/l)*term_const )\n",
    "\n",
    "# ==========================================\n",
    "# 3. PLOTTING\n",
    "# ==========================================\n",
    "fig, axs = plt.subplots(5, 1, figsize=(10, 15), sharex=True)\n",
    "plt.subplots_adjust(hspace=0.6)\n",
    "\n",
    "# 0. Free Body Diagram (FBD)\n",
    "ax = axs[0]\n",
    "ax.plot([0, l], [0, 0], 'black', lw=4) # Beam\n",
    "# Reactions R1 and R2\n",
    "ax.annotate(f'R1={R1:.0f}N', xy=(0, 0), xytext=(0, 0.5), arrowprops=dict(arrowstyle='->', lw=2, color='green'), ha='center')\n",
    "ax.annotate(f'R2={R2:.0f}N', xy=(l, 0), xytext=(l, 0.5), arrowprops=dict(arrowstyle='->', lw=2, color='green'), ha='center')\n",
    "# Distributed Load w\n",
    "ax.fill_between([a, l], [0, 0], [-0.4, -0.4], color='red', alpha=0.3)\n",
    "ax.text((a+l)/2, -0.6, f'w={w_load}N/m', color='red', ha='center', fontweight='bold')\n",
    "ax.axvline(a, color='red', linestyle=':', alpha=0.5) # Location dash\n",
    "ax.set_xticks([0, a, l])\n",
    "ax.xaxis.tick_top()\n",
    "ax.xaxis.set_label_position('top')\n",
    "ax.set_xlabel('Position x (m)')\n",
    "ax.set_ylim(-1, 1)\n",
    "ax.set_title('Free Body Diagram & Loading Condition', pad=40)\n",
    "ax.spines['left'].set_visible(False)\n",
    "ax.spines['right'].set_visible(False)\n",
    "ax.spines['bottom'].set_visible(False)\n",
    "ax.get_yaxis().set_visible(False)\n",
    "\n",
    "# 1. Shear\n",
    "axs[1].plot(x, V, 'r'); axs[1].fill_between(x, V, color='r', alpha=0.1); axs[1].set_ylabel('Shear (N)')\n",
    "axs[1].grid(True, alpha=0.3); axs[1].axhline(0, color='k', lw=1)\n",
    "\n",
    "# 2. Moment\n",
    "axs[2].plot(x, M, 'b'); axs[2].fill_between(x, M, color='b', alpha=0.1); axs[2].set_ylabel('Moment (Nm)')\n",
    "axs[2].grid(True, alpha=0.3); axs[2].axhline(0, color='k', lw=1)\n",
    "\n",
    "# 3. Slope\n",
    "axs[3].plot(x, theta, 'g'); axs[3].fill_between(x, theta, color='g', alpha=0.1); axs[3].set_ylabel('Slope (rad)')\n",
    "axs[3].grid(True, alpha=0.3); axs[3].axhline(0, color='k', lw=1)\n",
    "\n",
    "# 4. Deflection\n",
    "axs[4].plot(x, y*1000, 'purple'); axs[4].fill_between(x, y*1000, color='purple', alpha=0.1); axs[4].set_ylabel('Deflection (mm)')\n",
    "axs[4].grid(True, alpha=0.3); axs[4].axhline(0, color='k', lw=1); axs[4].set_xlabel('Position x (m)')\n",
    "\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('BeamAnalysisTool.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)
